### ISSUE TITLE
October dojo

### ISSUE THREAD

**Issue by joeldart** [coderdojoindy/coderdojo-meetings#10]
Who can be there? Last time we split into 3 groups 
- scratch walk throughs
- script craft
- coderdojoindy.com site

I don't believe I can be there this month.

Does that look like the way things should continue? I know C. is also interested in app development. We started looking at the jquery mobile framework since he knows js so well, but I think he needs to figure out what he wants to build first of to have some walk throughs to go through first.

For the site the next month, I was going to get them to start with a template from bootstrap and make the necessary changes to make it work for our site.

**Comment by jonnolen** [comment]
See #12 for details of what happened at the October Meetup.
