### ISSUE TITLE
Girls Inc Summer Camp 2014

### ISSUE THREAD

**Issue by jonnolen** [coderdojoindy/coderdojo-meetings#13]
LaTasha reached out for us to do the Girls Inc summer camp again.  This year we get 2 hours which is probably better.  Here are the proposed days/times:

Monday, June 23rd
9:30am-11:20am - 25-30 girls between the ages of 9-11

Tuesday, June 24th
9:30am-11:20am - 25-30 girls between the ages of 9-11

Wednesday, June 25th
9:30am-11:20am - 25-30 girls between the ages of 9-11

Thursday, June 26th
9:30am-11:20am - 25-30 girls between the ages of 9-11

Friday, June 27th
9:30am-11:20am - 25-30 girls between the ages of 9-11

**Comment by joeldart** [comment]
done like a year ago - discussion moved to https://github.com/coderdojoindy/GirlsIncWorkshop
