### ISSUE TITLE
Set up mx records for coderdojoindy.org

### ISSUE THREAD

**Issue by joeldart** [coderdojoindy/coderdojo-meetings#2]
Need to create an info account since its parents may not realize questions are going out to a mailing list.

**Comment by jonnolen** [comment]
who do you want to be on the list other than you and me?

**Comment by jonnolen** [comment]
also, my go to method of doing this is to just forward the emails to my account and then set up a forward rule to other people from there.

**Comment by joeldart** [comment]
I'd say put kyle in there too, but we should limit it there to avoid race
conditions. I used that method with givecamp emails and it works alright.
there are downsides, but none worth fighting for for our purposes. :+1:

**Comment by jonnolen** [comment]
@joeldart , forwarding request sent to drawingunicorns...  @shipstar do you prefer your personal gmail address or your shiplington email address?

**Comment by shipstar** [comment]
kyleashipley@gmail.com is probably preferred.

**Comment by jonnolen** [comment]
@shipstar verification email sent to you too.

**Comment by jonnolen** [comment]
I think this is complete.  you each should have gotten three test emails at around 3:50p today.  Let me know if you didn't.

**Comment by shipstar** [comment]
I didn't get any test emails that I see.

**Comment by joeldart** [comment]
Nor I

**Comment by jonnolen** [comment]
@joeldart @shipstar how about now?  three emails  test II .com||.org||.info

**Comment by joeldart** [comment]
Success!
