### ISSUE TITLE
Start kids working on coderdojoindy.org website

### ISSUE THREAD

**Issue by joeldart** [coderdojoindy/coderdojo-meetings#3]
We have several kids who would really enjoy working on a larger project like this. Current needs
- [ ] link to zen for sign ups
- [ ] showcase of recent work
- [ ] general about info for parents, members, and volunteers
- [ ] link to Google Group / other discussion board

**Comment by shipstar** [comment]
Maybe http://indystartuplab.org/ would be a reasonable analog?

**Comment by jonnolen** [comment]
site has it's own repo now: https://github.com/coderdojoindy/coderdojo-site
