### ISSUE TITLE
STEM activity for boys and girls club of america

### ISSUE THREAD

**Issue by joeldart** [coderdojoindy/coderdojo-meetings#9]
Yolanda from the Jack and Jill club of America is organizing a stem activity for 21 5th/6th grade boys and girls the last Saturday in Oct. there seems to be availability for the legacy center and the laptops, so she just needs our help on curriculum and volunteers. 

This would be a couple hour activity, so we could do either a scratch run through, breakout, or the js word scramble activity as those are the ones so far that take the full time with beginners. Still talking through what she wants.

This looks to be a lot of new faces and there will be good opportunity for outreach to the girls since this is in that ideal pre-self-selecting-out age group. What kind of availability do we have for volunteers?

**Comment by jonnolen** [comment]
I'm available.  I think that the js word scramble activity would probably be the most rewarding.

**Comment by joeldart** [comment]
they had to cancel the event and go with someone else. I'm figuring out the post-mortem where I went wrong, but either way this weekend is free.
